FROM prom/prometheus:latest

# Expose Prometheus UI/HTTP API
EXPOSE 9090

# Optional metadata
LABEL org.opencontainers.image.title="Prometheus" \
      org.opencontainers.image.description="Monitoring system & time series database" \
      org.opencontainers.image.source="https://github.com/prometheus/prometheus" \
      org.opencontainers.image.url="https://prometheus.io/"

