FROM grafana/grafana:latest

# Grafana listens on 3000 by default
EXPOSE 3000

# Optional metadata
LABEL org.opencontainers.image.title="Grafana" \
      org.opencontainers.image.description="Analytics & monitoring dashboard" \
      org.opencontainers.image.source="https://github.com/grafana/grafana" \
      org.opencontainers.image.url="https://grafana.com/"

