FROM nginx:1.27-alpine

# Set working directory where your app files will be mounted via compose
WORKDIR /usr/share/nginx/html

# Expose default HTTP port
EXPOSE 80

# Optional metadata
LABEL org.opencontainers.image.title="nginx" \
      org.opencontainers.image.description="Official NGINX image (Alpine)" \
      org.opencontainers.image.source="https://github.com/nginxinc/docker-nginx" \
      org.opencontainers.image.url="https://hub.docker.com/_/nginx"

